import { readFileSync } from 'node:fs';
import { SITE_URL, BOOKING_URL, LINKEDIN_COMPANY_URL, CF_ANALYTICS_TOKEN } from './config.mjs';

export const BOOK = BOOKING_URL || '/#contact';
// Booking links open the external Zoho Bookings page in a new tab; until BOOKING_URL is set they jump to the contact form.
// Email link (subject prefilled) plus a Copy button for visitors without a mail app. The button is shown only with JS (site.js).
export const MAILTO = 'mailto:hello@eonai.ai?subject=Enquiry%20from%20eonai.ai';
const copyIcon = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1"/></svg>';
export const emailWithCopy = (linkClass) => `<span class="email-row"><a class="${linkClass}" href="${MAILTO}">hello@eonai.ai</a><button class="copy-email" type="button" data-copy="hello@eonai.ai" aria-label="Copy email address">${copyIcon}<span class="copy-email__label">Copy</span></button></span>`;
export const BOOK_ATTRS = BOOKING_URL ? ' target="_blank" rel="noopener"' : '';
export const BOOK_SR = BOOKING_URL ? '<span class="visually-hidden"> (opens in a new tab)</span>' : '';
export const LINKEDIN = LINKEDIN_COMPANY_URL || '/#contact';

export const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// Logo: inlined from brand/logo (generated by brand/make-logo.py; see CLAUDE.md § Logo). Decorative here; the link carries the name.
const logoDark = readFileSync(new URL('../brand/logo/eonai-logo-on-dark.svg', import.meta.url), 'utf8')
  .trim().replace(/<title>.*?<\/title>/, '').replace(' role="img" aria-label="EonAI"', ' aria-hidden="true" focusable="false"');
export const logo = (cls) => logoDark.replace('<svg ', `<svg class="${cls}" `);

const NAV = [
  ['Problems we solve', '/#problems'],
  ['Services', '/#services'],
  ['How we work', '/#approach'],
  ['Engagements', '/#offers'],
  ['Engineering notes', '/notes/'],
];

function header(current) {
  const links = NAV.map(([label, href]) => {
    const cur = current === 'notes' && href === '/notes/' ? ' aria-current="page"' : '';
    return `<a href="${href}"${cur}>${label}</a>`;
  }).join('\n');
  return `<header class="site-header">
<div class="site-header__inner">
<a class="brand" href="/" aria-label="EonAI home">${logo('brand__logo')}</a>
<button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav">Menu</button>
<nav class="nav" id="site-nav" aria-label="Main">
${links}
<a class="btn btn--primary" href="${BOOK}"${BOOK_ATTRS}>Book a session${BOOK_SR}</a>
</nav>
</div>
</header>`;
}

function footer() {
  const todo = LINKEDIN_COMPANY_URL ? '' : '<!-- TODO: LINKEDIN_COMPANY_URL (src/config.mjs) -->';
  return `<footer class="site-footer">
<div class="site-footer__inner">
<div class="site-footer__brand">
<a class="site-footer__name" href="/" aria-label="EonAI home">${logo('site-footer__logo')}</a>
<span>Evaluation-first AI engineering for startups and enterprises.</span>
<span class="site-footer__legal">EonAI Private Limited · CIN U62011TS2025PTC203906<br>Plot No 4, Doc Bhavan, 4th &amp; 5th Floor, Madhapur, Hyderabad 500081, India</span>
</div>
<div class="site-footer__cols">
<div class="site-footer__col">
<strong>Company</strong>
<a href="/#problems">Problems we solve</a>
<a href="/#services">Services</a>
<a href="/#approach">How we work</a>
<a href="/#offers">Engagements</a>
<a href="/#about">About</a>
</div>
<div class="site-footer__col">
<strong>Contact</strong>
${emailWithCopy('site-footer__mail')}
${todo}<a href="${LINKEDIN}"${LINKEDIN_COMPANY_URL ? ' target="_blank" rel="noopener"' : ''}>LinkedIn${LINKEDIN_COMPANY_URL ? '<span class="visually-hidden"> (opens in a new tab)</span>' : ''}</a>
<a href="/privacy/">Privacy policy</a>
</div>
</div>
</div>
<div class="site-footer__copy">© 2026 EonAI Private Limited. All rights reserved.</div>
</footer>`;
}

/**
 * Wrap page content in the shared document shell.
 * opts: title, description, path (e.g. '/notes/'), current ('notes'), jsonLd (object|null), noindex, ogType
 */
export function page(opts, body) {
  const url = SITE_URL + opts.path;
  const jsonLd = opts.jsonLd ? `\n<script type="application/ld+json">${JSON.stringify(opts.jsonLd)}</script>` : '';
  const analytics = CF_ANALYTICS_TOKEN
    ? `\n<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"token": "${CF_ANALYTICS_TOKEN}"}'></script>`
    : '';
    const canonical = opts.noCanonical ? '' : `\n<link rel="canonical" href="${url}">`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script>document.documentElement.classList.add('js')</script>
<title>${esc(opts.title)}</title>
<meta name="description" content="${esc(opts.description)}">${canonical}
<meta property="og:site_name" content="EonAI">
<meta property="og:type" content="${opts.ogType || 'website'}">
<meta property="og:title" content="${esc(opts.title)}">
<meta property="og:description" content="${esc(opts.description)}">
<meta property="og:url" content="${url}">
<meta property="og:image" content="${SITE_URL}/assets/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="eonai logo. AI that works beyond the demo">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(opts.title)}">
<meta name="twitter:description" content="${esc(opts.description)}">
<meta name="twitter:image" content="${SITE_URL}/assets/og.png">
<meta name="theme-color" content="#0B1220">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="preload" href="/assets/fonts/plex-sans.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/space-grotesk.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/assets/fonts/plex-mono-400.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="/assets/site.css">${jsonLd}
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
${header(opts.current)}
<main id="main">
${body}
</main>
${footer()}
<script src="/assets/site.js" defer></script>${analytics}
</body>
</html>
`;
}
